home:
    route: "/"
    allowed_methods: ['get']
some-page:
    route: "/some-page"
    allowed_methods: ['get']

some-{variable}-page:
    route: "/some/{variable}/page"
    allowed_methods: ['get']